name: Build Workflow

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ./artifacts

      - name: Maven Build
        run: |
          # Your build commands go here
          echo "Listing out the content...."
          ls -latr
          echo "Performing maven clean test...."
          mvn clean test
          echo "Performing maven clean package...."
          mvn clean package -DskipTests
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/*.jar
          retention-days: 2
