name: Build Workflow

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here
      - name: Maven Build
        run: |
          # Your build commands go here
          echo "Performing maven clean test...."
          maven clean test
          echo "Performing maven clean package...."
          maven clean package -DskipTests
