name: Build Workflow

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here
      - name: Build your project
        run: |
          # Your build commands go here
          echo "Building your project..."
