name: Checkout Workflow

on:
  workflow_call:
    inputs:
      myOutput: ${{ steps.step1.outputs.myOutput }}

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      myOutput: ${{ steps.step1.outputs.myOutput }}
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "::set-output name=myOutput::Hello from Job 1"
