name: Checkout Workflow

on:
  workflow_call:
    inputs:
      myOutput:
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 2
        run: |
          echo "Received output from Job 1: ${{ github.event.inputs.myOutput }}"
