name: Create Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          curl -L -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer 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"   https://api.github.com/repos/ankgoya1/pr/pulls   -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"featureankit","base":"main"}'
