name: Create Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.GIT_PASS }}

      - name: Create Pull Request
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/ankgoya1/pr/pulls -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"main","base":"featureankit"}'
