name: Create Pull Request

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4 * * *'  # Run every day at 4:10 AM IST (10:10 PM UTC)

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          echo "The current time is $(date +"%T")"
          response=$(curl -L -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.GIT_PASS }}"   https://api.github.com/repos/ankgoya1/pr/pulls   -d '{"title":"Amazing new feature2","body":"Please pull these awesome change in!","head":"featureankit","base":"main"}')
          pr_number=$(echo "$response" | jq -r '.number')
          curl -s -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GIT_PASS }}" https://api.github.com/repos/ankgoya1/pr/pulls/$pr_number/merge
