name: Create Pull Request

on:
  workflow_dispatch:
  push: 
    branches:
      - dev1
  schedule:
    - cron: "45 6 * * *"  # 11:45 AM IST in UTC

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: create pull request
        run: gh pr create -B dev1 -H qa --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_PASS }}
