name: Create Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        with:
          token: ${{ secrets.GIT_PASS }}

      - name: Create Pull Request
        run: |
          gh pr create -B dev1 -H qa --title 'Merge branch_to_merge into base_branch' --body 'Created by GitHub action'
