name: Publish Artifact Workflow

on:
  workflow_call:
    secrets:
      token:
        required: true
      pass:
        required: true
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          printenv # Print all environment variables for further debugging
          echo "value is ${{ secrets.token }}"
          echo "cloning repo....."
          git clone https://ankgoya1:${{ secrets.pass }}@github.com/ankgoya1/demorepo .git
          ls -latr
