name: Publish Artifact Workflow

on:
  workflow_call:
    inputs:
      # config-path:
      #   required: true
      #   type: string
    secrets:
      token:
        required: true
  
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          # echo "Received VAR: ${{ VAR }}"
          printenv # Print all environment variables for further debugging
          echo "value is ${{ secrets.token }}"
