name: Publish Artifact Workflow

on:
  workflow_call:
    inputs:
      VAR:
        required: true
        type: string  
env:
  Secret: ${{ secrets.USER }}
jobs:
  publish:
    runs-on: ubuntu-latest
    # env:
    #   MY_VAR: ${{ github.event.inputs.MY_VAR }}
    #   USER: ${{ github.event.inputs.USER }}
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Publishing the Artifacts..."
          echo "variable value is $Secret"
          # echo "secret value is $USER"
