name: Publish Artifact Workflow

on:
  workflow_call:
    secrets:
      token:
        required: true
      pass:
        required: true
    inputs:    
      user:
        description: Flag indicating whether the apps should be signed
        type: string 
      name: 
        type: string 
      mname:
        type: string
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Debug
      #   run: |
      #     echo "value is ${{ secrets.token }}"
      #     echo "This pipeline has been trigger by ${{ inputs.user }} ${{ inputs.mname }} ${{ inputs.name }}"
      #     echo "cloning repo....."
          #   git clone https://ankgoya1:${{ secrets.pass }}@github.com/ankgoya1/demorepo.git
          # cd demorepo
          # ls -latr

      - name: Trigger Workflow in repoA
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_PASS }}
          repository: ankgoya1/App1
          event-type: use-secret
          client-payload: '{"secretName": "GIT_PASS"}'
          run: | 
            echo "value is ${{ secrets.token }}"
            git clone https://ankgoya1:$token@github.com/ankgoya1/demorepo.git
            ls -latr
            cd demorepo
            ls -latr
