name: Publish Artifact Workflow

on:
  workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Publishing the Artifacts..."
          echo "variable value is ${{ env.My_Var }}"
          echo "secret value is $USER"
