name: Publish Artifact Workflow

on:
  workflow_call:
    inputs:
      VAR:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "Received VAR: ${{ github.event.inputs.VAR }}"
          printenv # Print all environment variables for further debugging
