name: Publish Artifact Workflow

on:
  workflow_call:
    inputs:
      VAR:
        required: true
        type: string
      USER_SECRET:
        required: true
        type: string

env:
  Secret: ${{ github.event.inputs.VAR }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    # env:
    #   MY_VAR: ${{ github.event.inputs.MY_VAR }}
    #   USER: ${{ github.event.inputs.USER }}
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Publish
        run: |
          echo "Publishing the Artifacts..."
          echo "Variable value is $Secret"
          echo "Secret value is ${{ github.event.inputs.USER_SECRET }}"
