name: Publish Artifact Workflow

on:
  workflow_call:
    secrets:
      token:
        required: true
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          printenv # Print all environment variables for further debugging
          echo "value is ${{ secrets.token }}"
