name: Publish Artifact Workflow

on:
  workflow_call:
    inputs:
      VAR:
        required: true
        type: string

env:
  Secret: ${{ github.event.inputs.VAR }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: |
          echo "Publishing the Artifacts..."
          echo "Variable value is ${{ github.event.inputs.VAR }}"
